name: Compilar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Comprobar Flutter
        run: flutter --version

      - name: Crear estructura Android si falta
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: URAPMIR-Android
          path: build/app/outputs/flutter-apk/app-release.apk
